### ISSUE TITLE
Swift 4 Conversion Issue

### ISSUE THREAD

**Issue by AniruddhaPol** [anatoliyv/SMIconLabel#8]
Getting NSFontAttributeName' has been renamed to 'NSAttributedStringKey.font' , error after converting to swift 4. My current version for SMIconLabel is 0.4.0.
![swift4_conversionissue](https://user-images.githubusercontent.com/6449188/34944245-ddb96be0-fa24-11e7-8b84-0509aaeb58d6.png)

**Comment by anatoliyv** [comment]
Fixed in v.0.5.0
